# Generated by Django 3.2.3 on 2021-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.AddField(
            model_name='files',
            name='comment',
            field=models.CharField(default='No Comments', max_length=50),
        ),
    ]
