# Generated by Django 3.2.3 on 2021-05-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_auto_20210530_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
